### ISSUE TITLE
不能运行

### ISSUE THREAD

**Issue by bicijinlian** [summerccc/Python_serial_debug#1]
使用VS Code 1.54.2
No module named '串口通讯'

**Comment by summerccc** [comment]
需要改一下文件夹名和需要安装串口库

**Comment by blayno** [comment]
hi i get the same error, No module named '串口通讯', how do i get it to work, thank you
嗨，我遇到了同樣的錯誤，沒有名為“串口通訊”的模塊，我該如何讓它工作，謝謝
